import Head from "next/head";
import { HomePage } from "../src/components/home/home-page";

export async function getServerSideProps() {
  try {
    const { events_categories } = await import("/data/data.json");
    console.log("events_categories", events_categories);
    return {
      props: {
        data: events_categories,
      },
    };
  } catch (error) {
    console.error("Error fetching data:", error);
    return {
      props: {
        data: null,
      },
    };
  }
}

export default function Home({ data }) {
  console.log("data", data);
  if (!data) {
    // Handle loading state, return a loading spinner, or a message
    return <div>Loading...</div>;
  }
  return (
    <div>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage data={data} />
    </div>
  );
}
