import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <img />
          <a href=""> Home</a>
          <a href="/events"> Events</a>
          <a href="/about-us"> About Us</a>
        </nav>
      </header>
      <main>
        <div>
          <a href="">
            <img />
            <h2>Events in London</h2>
            <p>
              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
              enim ad minim veniam, quis nostrud exercitation ullamco laboris
              nisi ut aliquip ex ea commodo consequat.
            </p>
          </a>
          <a href="">
            <img />
            <h2>Events in San Francisco</h2>
            <p>
              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
              enim ad minim veniam, quis nostrud exercitation ullamco laboris
              nisi ut aliquip ex ea commodo consequat.
            </p>
          </a>
          <a href="">
            <img />
            <h2>Events in Berlin</h2>
            <p>
              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
              enim ad minim veniam, quis nostrud exercitation ullamco laboris
              nisi ut aliquip ex ea commodo consequat.
            </p>
          </a>
        </div>
      </main>
      <footer>
        <p> © 2023 clmnt - A project built with Next.js</p>
      </footer>
    </div>
  );
}
