import Head from "next/head";
import Image from "next/image";

export async function getServerSideProps() {
  try {
    const { events_categories } = await import("/data/data.json");
    console.log("events_categories", events_categories); 
    return {
      props: {
        data: events_categories,
      },
    };
  } catch (error) {
    console.error("Error fetching data:", error);
    return {
      props: {
        data: null,
      },
    };
  }
}

export default function Home({ data }) {
  console.log("data", data);
  if (!data) {
    // Handle loading state, return a loading spinner, or a message
    return <div>Loading...</div>;
  }
  return (
    <div>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <img />
          <a href=""> Home</a>
          <a href="/events"> Events</a>
          <a href="/about-us"> About Us</a>
        </nav>
      </header>
      <main>
        {data?.map((ev) => (
          <a key={ev.id} href={`/event/${ev.id}`}>
            <Image width={200} height={200} alt={ev.title} src={ev.image} />
            <h2>{ev.title}</h2>
            <p>{ev.description}</p>
          </a>
        ))}
      </main>
      <footer>
        <p> © 2023 clmnt - A project built with Next.js</p>
      </footer>
    </div>
  );
}
